SELECT USER FROM DUAL;

SELECT username, osuser, machine
FROM v$session
WHERE username IS NOT NULL;

CREATE TABLESPACE Team_02_GreenDelivery
DATAFILE '/opt/oracle/oradata/XE/XEPDB1/Team_02_GreenDelivery.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 10M
MAXSIZE UNLIMITED;

SELECT TABLESPACE_NAME
FROM DBA_TABLESPACES
WHERE TABLESPACE_NAME = 'TEAM_02_GREENDELIVERY';

-- Crear usuario 1
CREATE USER GD_ADMIN IDENTIFIED BY orcladmin123
DEFAULT TABLESPACE Team_02_GreenDelivery
TEMPORARY TABLESPACE TEMP;

-- Crear usuario 2
CREATE USER GD_DEV IDENTIFIED BY orcldev123
DEFAULT TABLESPACE Team_02_GreenDelivery
TEMPORARY TABLESPACE TEMP;

-- Desbloquear cuentas de usuario
ALTER USER GD_ADMIN ACCOUNT UNLOCK;
ALTER USER GD_DEV ACCOUNT UNLOCK;

-- Asignar roles y privilegios de sistema
GRANT CONNECT, RESOURCE TO GD_ADMIN;
GRANT CONNECT, RESOURCE TO GD_DEV;

ALTER USER GD_ADMIN QUOTA UNLIMITED ON Team_02_GreenDelivery;
ALTER USER GD_DEV QUOTA UNLIMITED ON Team_02_GreenDelivery;

GRANT CREATE SESSION        TO GD_ADMIN;
GRANT CREATE TABLE          TO GD_ADMIN;
GRANT CREATE VIEW           TO GD_ADMIN;
GRANT CREATE PROCEDURE      TO GD_ADMIN;
GRANT CREATE TRIGGER        TO GD_ADMIN;
GRANT CREATE SEQUENCE       TO GD_ADMIN;
GRANT CREATE JOB            TO GD_ADMIN;
GRANT UNLIMITED TABLESPACE  TO GD_ADMIN;

-- permisos similares a GD_DEV
GRANT CREATE TABLE          TO GD_DEV;
GRANT CREATE VIEW           TO GD_DEV;
GRANT CREATE PROCEDURE      TO GD_DEV;
GRANT CREATE TRIGGER        TO GD_DEV;
GRANT CREATE SEQUENCE       TO GD_DEV;
GRANT CREATE JOB            TO GD_DEV;

SELECT USERNAME, DEFAULT_TABLESPACE, TEMPORARY_TABLESPACE
FROM DBA_USERS
WHERE USERNAME IN ('GD_ADMIN', 'GD_DEV');
