-------------------------------------------------
-- TABLA: DELIVERIES
-------------------------------------------------
CREATE TABLE deliveries (
    id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departure_time  TIMESTAMP,
    delivery_time   TIMESTAMP,
    delivery_cost   NUMBER(8,2),
    distance_travel NUMBER(6,2),
    status          CHAR(1),
    orders_id       NUMBER NOT NULL
);

-- Restricciones de deliveries
ALTER TABLE deliveries ADD CONSTRAINT ck_deliveries_cost CHECK (delivery_cost >= 0 OR delivery_cost IS NULL);
ALTER TABLE deliveries ADD CONSTRAINT ck_deliveries_distance CHECK (distance_travel >= 0 OR distance_travel IS NULL);
ALTER TABLE deliveries ADD CONSTRAINT ck_deliveries_status CHECK (status IN ('P','E','C','X')); 
-- P=Pendiente, E=En curso, C=Completado, X=Cancelado

-- Índices de deliveries
CREATE INDEX idx_deliveries_status ON deliveries(status);
CREATE INDEX idx_deliveries_order ON deliveries(orders_id);


-------------------------------------------------
-- TABLA: ROUTES
-------------------------------------------------
CREATE TABLE routes (
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR2(150) NOT NULL,
    description        VARCHAR2(250),
    main_district      VARCHAR2(100),
    distance_km        NUMBER(6,2),
    estimated_time_min NUMBER,
    difficulty         VARCHAR2(15),
    date_register      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status             CHAR(1) DEFAULT 'A' NOT NULL
);

-- Restricciones de routes
ALTER TABLE routes ADD CONSTRAINT ck_routes_distance CHECK (distance_km > 0 OR distance_km IS NULL);
ALTER TABLE routes ADD CONSTRAINT ck_routes_time CHECK (estimated_time_min > 0 OR estimated_time_min IS NULL);
ALTER TABLE routes ADD CONSTRAINT ck_routes_status CHECK (status IN ('A','I'));
ALTER TABLE routes ADD CONSTRAINT ck_routes_difficulty CHECK (difficulty IN ('Fácil','Media','Difícil') OR difficulty IS NULL);

-- Índices de routes
CREATE INDEX idx_routes_status ON routes(status);
CREATE INDEX idx_routes_difficulty ON routes(difficulty);


-------------------------------------------------
-- TABLA: ROUTES_POINTS
-------------------------------------------------
CREATE TABLE routes_points (
    id                     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    routes_id              NUMBER NOT NULL,
    "order"                NUMBER,
    name                   VARCHAR2(50),
    description            VARCHAR2(250),
    latitude               NUMBER(10,8),
    length                 NUMBER(11,8),
    point_type             VARCHAR2(20),
    estimated_time_minutes NUMBER,
    distance_meters        NUMBER,
    observation            VARCHAR2(250),
    date_register          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status                 CHAR(1) DEFAULT 'A' NOT NULL
);

-- Restricciones de routes_points
ALTER TABLE routes_points ADD CONSTRAINT ck_routes_points_status CHECK (status IN ('A','I'));
ALTER TABLE routes_points ADD CONSTRAINT ck_routes_points_time CHECK (estimated_time_minutes > 0 OR estimated_time_minutes IS NULL);
ALTER TABLE routes_points ADD CONSTRAINT ck_routes_points_distance CHECK (distance_meters >= 0 OR distance_meters IS NULL);

-- Relación con routes
ALTER TABLE routes_points
ADD CONSTRAINT fk_routes_points_routes FOREIGN KEY (routes_id) REFERENCES routes(id) ON DELETE CASCADE;

-- Índices de routes_points
CREATE INDEX idx_routes_points_status ON routes_points(status);
CREATE INDEX idx_routes_points_route ON routes_points(routes_id);


-------------------------------------------------
-- TABLA: DELIVERY_ROUTES
-------------------------------------------------
CREATE TABLE delivery_routes (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    deliveries_id    NUMBER NOT NULL,
    routes_id        NUMBER NOT NULL,
    usage_type       CHAR(1),
    deviations       NUMBER,
    actual_time_min  NUMBER,
    actual_distance_k NUMBER(6,2),
    route_rating     NUMBER,
    usage_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    remarks          VARCHAR2(200)
);

-- Restricciones de delivery_routes
ALTER TABLE delivery_routes ADD CONSTRAINT ck_delivery_routes_usage CHECK (usage_type IN ('P','A','R') OR usage_type IS NULL); 
-- P=Principal, A=Alternativa, R=Respaldo
ALTER TABLE delivery_routes ADD CONSTRAINT ck_delivery_routes_time CHECK (actual_time_min >= 0 OR actual_time_min IS NULL);
ALTER TABLE delivery_routes ADD CONSTRAINT ck_delivery_routes_distance CHECK (actual_distance_k >= 0 OR actual_distance_k IS NULL);
ALTER TABLE delivery_routes ADD CONSTRAINT ck_delivery_routes_rating CHECK (route_rating BETWEEN 1 AND 5 OR route_rating IS NULL);
