CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    users_id NUMBER NOT NULL,
    order_code VARCHAR2(20) NOT NULL,
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    requested_delivery_date DATE,
    priority CHAR(1) DEFAULT 'N' NOT NULL,
    subtotal NUMBER(10,2) DEFAULT 0.00,
    shipping_cost NUMBER(8,2) DEFAULT 0.00,
    total NUMBER(10,2) DEFAULT 0.00,
    status CHAR(1) DEFAULT 'R' NOT NULL
);

-- Restricciones de la tabla orders
ALTER TABLE orders ADD CONSTRAINT uk_orders_code UNIQUE (order_code);
ALTER TABLE orders ADD CONSTRAINT ck_orders_priority CHECK (priority IN ('B','N','A','U'));
ALTER TABLE orders ADD CONSTRAINT ck_orders_status CHECK (status IN ('R','C','P','T','E','X'));
ALTER TABLE orders ADD CONSTRAINT ck_orders_amounts CHECK (subtotal >= 0 AND shipping_cost >= 0 AND total >= 0);
ALTER TABLE orders ADD CONSTRAINT ck_orders_total CHECK (total = subtotal + shipping_cost);
ALTER TABLE orders ADD CONSTRAINT ck_orders_delivery_date CHECK (requested_delivery_date >= TRUNC(order_date));
ALTER TABLE orders ADD CONSTRAINT ck_orders_code_format CHECK (REGEXP_LIKE(order_code, '^[A-Z0-9\-]+$'));

-- Índices para orders
CREATE INDEX idx_orders_client ON orders(users_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_date ON orders(order_date);
CREATE INDEX idx_orders_priority ON orders(priority);

-- TABLA DE DETALLE DE PEDIDOS

CREATE TABLE order_details (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orders_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 1 NOT NULL,
    unit_price NUMBER(10,2)
);

-- Restricciones de la tabla order_details
ALTER TABLE order_details ADD CONSTRAINT ck_order_details_quantity CHECK (quantity > 0);
ALTER TABLE order_details ADD CONSTRAINT ck_order_details_price CHECK (unit_price >= 0 OR unit_price IS NULL);


-- TABLA DE PRODUCTOS

CREATE TABLE product (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orders_id NUMBER NOT NULL,
    code VARCHAR2(20) NOT NULL,
    name VARCHAR2(30) NOT NULL,
    description VARCHAR2(100),
    unit_weight NUMBER(6,3),
    fragile CHAR(1) DEFAULT 'N' NOT NULL,
    cooled CHAR(1) DEFAULT 'N' NOT NULL,
    reference_price NUMBER(10,2),
    date_register TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status CHAR(1) DEFAULT 'A' NOT NULL
);

-- Restricciones de la tabla product
ALTER TABLE product ADD CONSTRAINT uk_product_code UNIQUE (code);
ALTER TABLE product ADD CONSTRAINT ck_product_fragile CHECK (fragile IN ('S','N')); -- S=Sí, N=No
ALTER TABLE product ADD CONSTRAINT ck_product_cooled CHECK (cooled IN ('S','N')); -- S=Sí, N=No
ALTER TABLE product ADD CONSTRAINT ck_product_status CHECK (status IN ('A','I')); -- A=Activo, I=Inactivo
ALTER TABLE product ADD CONSTRAINT ck_product_weight CHECK (unit_weight > 0 OR unit_weight IS NULL);
ALTER TABLE product ADD CONSTRAINT ck_product_price CHECK (reference_price >= 0 OR reference_price IS NULL);
ALTER TABLE product ADD CONSTRAINT ck_product_name_length CHECK (LENGTH(name) >= 2);

CREATE TABLE status_tracking (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    orders_id NUMBER NOT NULL,
    previous_status VARCHAR2(20),
    new_status VARCHAR2(20) NOT NULL,
    "comment" VARCHAR2(200),
    "user" VARCHAR2(100),
    change_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Restricciones de la tabla status_tracking
ALTER TABLE status_tracking ADD CONSTRAINT ck_st_statuses_different CHECK (previous_status != new_status OR previous_status IS NULL);

-- INSERTS PARA LA TABLA ORDERS
INSERT INTO orders (users_id, order_code, order_date, requested_delivery_date, priority, subtotal, shipping_cost, total, status)
VALUES (1, 'ORD-2025-001', TIMESTAMP '2025-09-28 14:30:00', DATE '2025-09-30', 'A', 150.00, 15.50, 165.50, 'E');

INSERT INTO orders (users_id, order_code, order_date, requested_delivery_date, priority, subtotal, shipping_cost, total, status)
VALUES (2, 'ORD-2025-002', TIMESTAMP '2025-09-28 16:45:00', DATE '2025-10-01', 'N', 280.00, 20.00, 300.00, 'E');

INSERT INTO orders (users_id, order_code, order_date, requested_delivery_date, priority, subtotal, shipping_cost, total, status)
VALUES (3, 'ORD-2025-003', TIMESTAMP '2025-09-29 09:15:00', DATE '2025-10-02', 'U', 450.00, 25.00, 475.00, 'T');


-- INSERTS PARA LA TABLA PRODUCT
INSERT INTO product (orders_id, code, name, description, unit_weight, fragile, cooled, reference_price, status)
VALUES (1, 'PROD-001', 'Laptop Dell Inspiron', 'Computadora portátil 15 pulgadas', 2.500, 'S', 'N', 1500.00, 'A');

INSERT INTO product (orders_id, code, name, description, unit_weight, fragile, cooled, reference_price, status)
VALUES (2, 'PROD-002', 'Smartphone Samsung', 'Teléfono inteligente Galaxy S23', 0.195, 'S', 'N', 899.99, 'A');

INSERT INTO product (orders_id, code, name, description, unit_weight, fragile, cooled, reference_price, status)
VALUES (3, 'PROD-003', 'Medicamento Refrigerado', 'Vacuna COVID-19 - Requiere cadena de frío', 0.050, 'S', 'S', 50.00, 'A');


-- INSERTS PARA LA TABLA ORDER_DETAILS
INSERT INTO order_details (orders_id, quantity, unit_price)
VALUES (1, 1, 150.00);

INSERT INTO order_details (orders_id, quantity, unit_price)
VALUES (2, 2, 140.00);

INSERT INTO order_details (orders_id, quantity, unit_price)
VALUES (3, 5, 90.00);


-- INSERTS PARA LA TABLA STATUS_TRACKING
INSERT INTO status_tracking (orders_id, previous_status, new_status, "comment", "user", change_date)
VALUES (1, 'R', 'C', 'Pedido confirmado y verificado por el sistema', 'admin_user', TIMESTAMP '2025-09-28 14:35:00');

INSERT INTO status_tracking (orders_id, previous_status, new_status, "comment", "user", change_date)
VALUES (1, 'C', 'P', 'Pedido preparado para envío', 'warehouse_staff', TIMESTAMP '2025-09-28 15:20:00');

INSERT INTO status_tracking (orders_id, previous_status, new_status, "comment", "user", change_date)
VALUES (1, 'P', 'T', 'Pedido en ruta de entrega', 'delivery_system', TIMESTAMP '2025-09-29 08:30:00');
